### PR TITLE
CSS Fix, Added Optional Chaining, Added Backend Drop pada call

### LINKED ISSUE #53: Add optional chaining back
Example: [this](https://github.com/UWO-Aero-Design/gnd-station/blob/d35716654f3db733db90bd39a16b1355ea0a4d34/frontend/src/components/TelemetryStatus.js#L6) will crash the frontend if the telemetry property or the battery property are undefined.

Looks like we can use optional chaining so add that back in and think of suitable defaults for each parameter when undefined (eg. altimeter should read "---" when undefined and not 0, since 0 ft is a valid altitude)

### LINKED ISSUE #54: Clean up Altimeter component
Remove unused code in [Altimeter](https://github.com/UWO-Aero-Design/gnd-station/blob/d35716654f3db733db90bd39a16b1355ea0a4d34/frontend/src/components/Altimeter.js) component.

- [ReadAltitude](https://github.com/UWO-Aero-Design/gnd-station/blob/d35716654f3db733db90bd39a16b1355ea0a4d34/frontend/src/components/Altimeter.js#L75-L79) isn't needed since telemetry is passed to the object
- [dropHeight](https://github.com/UWO-Aero-Design/gnd-station/blob/d35716654f3db733db90bd39a16b1355ea0a4d34/frontend/src/components/Altimeter.js#L11) should be passed in as a prop with a default value if not passed in. It should still be a stateful object (useState) since the prop can be updated during runtime
- [reset](https://github.com/UWO-Aero-Design/gnd-station/blob/d35716654f3db733db90bd39a16b1355ea0a4d34/frontend/src/components/Altimeter.js#L27-L30) should reset drop height to the passed in value not a constant
- [altitude and setAltitude](https://github.com/UWO-Aero-Design/gnd-station/blob/d35716654f3db733db90bd39a16b1355ea0a4d34/frontend/src/components/Altimeter.js#L12) are no longer needed
- [drop](https://www.quirksmode.org/css/units-values/viewport.html) should update with the right drop height

Run all tests using the new backend web socket (run `docker compose up api` from the root level of the repo

### LINKED ISSUE #55: CSS Cleanup
- There should be no scrolling. Entire screen should be [the width of vw and height of vh](https://www.quirksmode.org/css/units-values/viewport.html)
- PADA drop altitude should be centred
- TelemetryStatus needs to be clean up to match the mockup. There is a new telemetry protocol in the works and this component may have telemetry items added/removed so plan for it to be dynamic
- Header isn't needed as there will be a logo in the centre top location

### LINKED ISSUE #56: Drop PADA button should make the correct call to the backend
Use `docker compose up api` and visit [http://localhost:5000/docs](http://localhost:5000/docs) to view all end points. The required endpoint with example is under Commands > [POST] Send Command(s)

### PR DESCRIPTION
**Pull request by john-langlois**

### CODE REVIEW

File: frontend/src/App.js [hunk 1]
```diff
@@ -28,59 +27,91 @@ function App() {
...
       setTelemetry(telemetry);
-      console.log(data);
+      //console.log(data);
     }
 
   },[]);
 
+  const success = () =>{
+    //Add overlay to show success message
+  }
```
Comment (jeffstjean) [inline frontend/src/App.js:37]: rename to `displaySuccessMessage`

File: frontend/src/App.js [hunk 2]
```diff
@@ -28,59 +27,91 @@ function App() {
...
+  const errorMessage = () =>{
+    //Add overlay to show error message
+  }
```
Comment (jeffstjean) [inline frontend/src/App.js:40]: rename to `displayErrorMessage`, should accept two strings as an argument.

The first argument will be `error` which is an arbitrarily defined string that is the "error type" (eg. for an invalid command, it might be "InvalidCommand" - each word capitalized with no spaces).

The second argument will be `error_message` which is another string this time as a human readable string (eg. "The provided command is invalid."). 

This will then get displayed as `<error>: <error_message>` (eg. InvalidCommand: The provided command is invalid.).

This makes it easy to search through the code for `InvalidCommand` to find which lines of code caused it.

File: frontend/src/App.js [hunk 3]
```diff
@@ -28,59 +27,91 @@ function App() {
...
+
+  //add http request for command to backend
+  //Backend call for command using http request
+  const getCommand = async(command, args) => {
+    console.log("drop pada function")
```
Comment (jeffstjean) [inline frontend/src/App.js:45]: remove

File: frontend/src/components/Altimeter.js [hunk 4]
```diff
@@ -5,43 +5,60 @@ import Button from "./Button";
 
 // #00e676 #00c853
 
-function Altimeter({telemetry}) {
+function Altimeter({telemetry, command}) {
+//Declare altitude variable outside to be able to restrain it to 2 decimals per
+    //has to parseFloat, otherwise gives undefined error with toFixed function.
+    let alt = telemetry === undefined ? "---" : (telemetry.enviro?.altitude);
+    let altDisplay = parseFloat(alt).toFixed(2);
```
Comment (jeffstjean) [inline frontend/src/components/Altimeter.js:12]: alt is eventually compared as a numerical value to determine if it is at a valid drop height. This leads to "---" being compared to the drop threshold which isn't good (string compared to number?). Instead let's deal with the initial situation where no data has been received yet by having the `canDrop()` return false until a packet has been received and altDisplay be "---" until a packet has been received. This can be achieved by using a bool that will act as a flag for "first_packet_received". As soon as enviro isn't undefined, set the flag to true. Then, use the flag in `canDrop()` and altDisplay

**Review by jeffstjean — APPROVED** [review]
